[package]
name = "msd-companion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
printpdf = "0.7.0"
serde = {version = "1.0.198", features=["derive"]}
